project_name: kustomize-sopssecretgenerator

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

env_files:
  github_token: .githuub_token

before:
  hooks:
    - go mod tidy

builds:
  - binary: SopsSecretGenerator

archives:
  - format: binary

release:
  github:
    owner: goabout
    name: kustomize-sopssecretgenerator
  name_template: "Version {{.Version}}"
