project_name: kustomize-sopssecretgenerator

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

env_files:
  github_token: .github_token

gomod:
  proxy: true

before:
  hooks:
    - go mod tidy

builds:
  - binary: SopsSecretGenerator
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: binary

changelog:
  filters:
    exclude:
      - '^Release version'
      - '^Merge pull request'

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: goabout
    name: kustomize-sopssecretgenerator
  name_template: "Version {{.Version}}"
