project_name: kustomize-sopssecretgenerator

env:
  - GO111MODULE=on

env_files:
  github_token: .github_token

before:
  hooks:
    - go mod tidy

builds:
  - binary: SopsSecretGenerator
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
  - format: binary

changelog:
  filters:
    exclude:
      - '^Release version'

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: goabout
    name: kustomize-sopssecretgenerator
  name_template: "Version {{.Version}}"
